baseURL: https://there-and-back.org/
languageCode: en-us
title: There and back
theme: "PaperMod"
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
minify:
  disableXML: true
  minifyOutput: true
params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: There and back
  description: "A family's writing and photography"
  keywords: [Janet Reider, Matthew Reider, Deborah Green]
  # author: ["Me", "You"] # multiple authors
  DateFormat: "January 2, 2006"
  defaultTheme: light # dark, light
  disableThemeToggle: true
  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: false
  disableSpecial1stPost: true
  disableScrollToTop: true
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false
  homeInfoParams:
    Title: "Welcome"
    Content: Our family's writing and photography.
    cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page
  profileMode:
    enabled: true
    title: "Welcome" # optional default will be site title
    subtitle: "Our family's writing and photography"
    imageUrl: "images/truck.png" # optional
    imageWidth: 150 # custom size
    imageHeight: 150 # custom size
    buttons:
        - name: Deb Green
          url: "/people/deb-green"
        - name: Janet Reider
          url: "/people/matt-reider"
        - name: Jenny Sampson
          url: "/people/jenny-sampson"
        - name: Pete Reider
          url: "/people/pete-reider"    
        - name: Pete Reider
          url: "/people/matt-reider"   
menu:
  main:
    - identifier: people
      name: people
      url: /people/
      weight: 1
    - identifier: tags
      name: tags
      url: /tags/
      weight: 2